# Generated by Django 3.0.6 on 2020-05-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_municipios_saopaulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipios',
            options={'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='saopaulo',
            options={'verbose_name_plural': 'SaoPaulo'},
        ),
        migrations.RenameField(
            model_name='municipios',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='saopaulo',
            old_name='item_id',
            new_name='id',
        ),
    ]
