# Generated by Django 3.0.6 on 2020-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20200521_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saopaulo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
